### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Neoner161** [BenTimor/Trading212API#7]
hey guys, can someone help me make this script to work?

**Comment by Doncharless** [comment]
> hey guys, can someone help me make this script to work? i am even able to pay for it, thanks

The best hacker who helped me with that I will advise message him on telegram
https://t.me/Blackhathacker110

**Comment by BenTimor** [comment]
Hey, this is not the place to look for paid services, and for sure not to promote hackers.
This project is archived for reasons, if someone wants to fork it he's welcome.
